### ISSUE TITLE
/v1/chat/completions 偶尔报 400 Bad Request 

### ISSUE THREAD

**Issue by bushkarl** [Grt1228/chatgpt-java#170]
2023-06-23 15:32:21.696  INFO 13361 --- [OkHttp https://openai.com/...]-[]-[]-[]-[] c.u.chatgpt.interceptor.OpenAILogger     : OkHttp-------->:<-- 400 Bad Request https://openai.com/v1/chat/completions (1578ms)

client 1.0.12版本

**Comment by briqt** [comment]
同样遇到。

**Comment by briqt** [comment]
同样遇到
retrofit2.adapter.rxjava2.HttpException: HTTP 400 Bad Request
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.blockingGet(Single.java:2869)
	at com.unfbx.chatgpt.OpenAiClient.chatCompletion(OpenAiClient.java:658)

**Comment by Grt1228** [comment]
@bushkarl @briqt  请求参数有么？贴一下

**Comment by bushkarl** [comment]
`{"model":"gpt-3.5-turbo","messages":[{"role":"user","content":"杭州旅游攻略来一份"},{"role":"assistant","content":"当然！以下是一份杭州旅游攻略：Day1: 西湖区- 上午：抵达杭州后，前往西湖区。可
以选择步行或租一辆自行车环湖游览。途中可以欣赏湖光山色，参观三潭印月、花港观鱼等景点。- 中午：在西湖附近的餐馆品尝当地美食，如西湖醋鱼、龙井虾仁等。- 下午：游览雷峰塔，登上塔顶俯瞰西湖全景。随后，可以前往南宋御街，逛逛古色古香的街道，品尝
小吃和购买纪念品。- 晚上：在西湖音乐喷泉广场欣赏音乐喷泉表演，结束一天的行程。Day2: 城市文化与自然风光- 上午：参观灵隐寺，感受佛教文化的庄严与宁静。随后，前往西溪湿地，漫步在湿地公园内，欣赏自然风光。- 中午：在西溪湿地附近的餐馆品尝杭州传
统菜肴，如东坡肉、叫花鸡等。- 下午：乘坐旅游大巴前往千岛湖，游览湖上的岛屿，欣赏湖光山色。可以选择乘船游览或租一辆自行车环湖游玩。- 晚上：返回杭州市区，在杭州大厦或湖滨银泰附近的餐馆品尝杭州美食，如葱包桧、西湖醋鱼等。Day3: 文化古镇与美食
之旅- 上午：乘坐旅游大巴前往乌镇，游览古镇的水乡风光和古建筑，参观吴门书院等景点。- 中午：在乌镇品尝当地特色美食，如河鲜、桂花糕等。- 下午：返回杭州市区，参观中国茶文化博物馆，了解茶文化的历史和发展。随后，可以前往杭州宋城景区，体验宋代文
化和建筑风格。- 晚上：在宋城景区内的餐厅品尝传统的宋代美食，享受古代文化的氛围。以上是一个简要的杭州旅游攻略，根据自己的兴趣和时间可以进行适当调整。祝您在杭州度过愉快的旅程！"},{"role":"user","content":"三天两晚行程<U+2757>Day1:威海站—韩
乐坊—火炬八街—国际海水浴场—欧乐坊夜市<U+1F696>：出行一整天为网约车或步行·【中午】抵达威海站后步行至斯维登度假公寓（韩乐坊店），放下行李后下楼至源味牛肉汤饭（韩乐坊店）用午餐。<U+1F4DD>住宿约64r/人，午饭约55r/人【下午】打卡威海“小镰仓”
<U+1F4CD>火炬八街，步行至<U+1F4CD>国际海水浴场 看日落。<U+1F4DD>景区无门票，打的费用为22r/人【晚上】打车至<U+1F4CD>欧乐坊夜市 吃特色小吃，最后回到公寓。<U+1F4DD>景区无门票，打的费用为21r/人，晚餐为43r/人‼day1费用合计205！··Day2:韩乐坊—那
香海—鸡鸣岛—韩乐坊夜市<U+1F696>：出行为网约车/轮渡/共享电动车·【上午】：从韩乐坊打车至<U+1F4CD>那香海 观看钻石沙滩享受阳光与大海。<U+1F4DD>景区无门票，住宿约64r/人，打车费用约为30r/人【中午】：步行至<U+1F37D>滨海壹号海景餐厅吃午饭。
<U+1F4DD>午饭费用约为112r/人【下午】：从那香海骑车到<U+1F4CD>那香海·鸡鸣岛登船处 乘坐轮渡抵达鸡鸣岛。打卡<U+1F4CD>鸡鸣岛的悬崖咖啡厅等特色建筑。<U+1F4DD>轮渡票为88r/人【晚上】：返回韩乐坊，吃特色韩料<U+1F37D>韩香福烤肉庄园。<U+1F4DD>打车
费用约为30r/人，晚饭费用约为118r/人‼day2费用合计442！··Day3:韩乐坊—半月湾—古陌早市—公寓—威海站<U+1F696>:出行为网约车·【清晨】：从公寓打的至<U+1F4CD>半月湾 欣赏日出。<U+1F4DD>景点无门票，打车费用约为12r/人【上午】：打车至<U+1F4CD>古陌早市
吃早餐，回酒店收拾行李回家。<U+1F4DD>打车费用约为17r/人，早餐费用约为30r/人。‼day3费用合计59r！参照上述文案，写一份杭州旅游攻略"},{"role":"assistant","content":"Day1: 西湖区- 上午：抵达杭州后，前往西湖区。可以选择步行或租一辆自行车环湖游
览。途中可以欣赏湖光山色，参观三潭印月、花港观鱼等景点。- 中午：在西湖附近的餐馆品尝当地美食，如西湖醋鱼、龙井虾仁等。- 下午：游览雷峰塔，登上塔顶俯瞰西湖全景。随后，可以前往南宋御街，逛逛古色古香的街道，品尝小吃和购买纪念品。- 晚上：在西
湖音乐喷泉广场欣赏音乐喷泉表演，结束一天的行程。Day2: 城市文化与自然风光- 上午：参观灵隐寺，感受佛教文化的庄严与宁静。随后，前往西溪湿地，漫步在湿地公园内，欣赏自然风光。- 中午：在西溪湿地附近的餐馆品尝杭州传统菜肴，如东坡肉、叫花鸡等。-
下午：乘坐旅游大巴前往千岛湖，游览湖上的岛屿，欣赏湖光山色。可以选择乘船游览或租一辆自行车环湖游玩。- 晚上：返回杭州市区，在杭州大厦或湖滨银泰附近的餐厅品尝杭州美食，如葱包桧、西湖醋鱼等。Day3: 文化古镇与美食之旅- 上午：乘坐旅游大巴前往乌
镇，游览古镇的水乡风光和古建筑，参观吴门书院等景点。- 中午：在乌镇品尝当地特色美食，如河鲜、桂花糕等。- 下午：返回杭州市区，参观中国茶文化博物馆，了解茶文化的历史和发展。随后，可以前往杭州宋城景区，体验宋代文化和建筑风格。- 晚上：在宋城景
区内的餐厅品尝传统的宋代美食，享受古代文化的氛围。以上是一个简要的杭州旅游攻略，根据自己的兴趣和时间可以进行适当调整。祝您在杭州度过愉快的旅程！"},{"role":"user","content":"Day1: 西湖区- 上午：抵达杭州后，前往西湖区。可以选择步行或租一辆
自行车环湖游览。途中可以欣赏湖光山色，参观三潭印月、花港观鱼等景点。- 中午：在西湖附近的餐馆品尝当地美食，如西湖醋鱼、龙井虾仁等。- 下午：游览雷峰塔，登上塔顶俯瞰西湖全景。随后，可以前往南宋御街，逛逛古色古香的街道，品尝小吃和购买纪念品。
- 晚上：在西湖音乐喷泉广场欣赏音乐喷泉表演，结束一天的行程。Day2: 城市文化与自然风光- 上午：参观灵隐寺，感受佛教文化的庄严与宁静。随后，前往西溪湿地，漫步在湿地公园内，欣赏自然风光。- 中午：在西溪湿地附近的餐馆品尝杭州传统菜肴，如东坡肉、
叫花鸡等。- 下午：乘坐旅游大巴前往千岛湖，游览湖上的岛屿，欣赏湖光山色。可以选择乘船游览或租一辆自行车环湖游玩。- 晚上：返回杭州市区，在杭州大厦或湖滨银泰附近的餐厅品尝杭州美食，如葱包桧、西湖醋鱼等。Day3: 文化古镇与美食之旅- 上午：乘坐旅
游大巴前往乌镇，游览古镇的水乡风光和古建筑，参观吴门书院等景点。- 中午：在乌镇品尝当地特色美食，如河鲜、桂花糕等。- 下午：返回杭州市区，参观中国茶文化博物馆，了解茶文化的历史和发展。随后，可以前往杭州宋城景区，体验宋代文化和建筑风格。- 晚
上：在宋城景区内的餐厅品尝传统的宋代美食，享受古代文化的氛围。把这份攻略的具体花费写一下！"}],"temperature":0,"topP":1,"n":1,"stream":false,"maxTokens":1200,"presencePenalty":0,"frequencyPenalty":0}

`


看了下主要可能因为报文里有特殊字符，导致json格式解析失败

**Comment by zhangzexing** [comment]
@Grt1228 加1，我也会，我在做chatpdf的功能，解析出来的pdf文件有特殊字符，直接HTTP 400 Bad Request报错

**Comment by Hwongyohong** [comment]
我也报了retrofit2.adapter.rxjava2.HttpException: HTTP 400 Bad Request的错误
