### ISSUE TITLE
...

### ISSUE THREAD

**Issue by youshandefeiyang** [Grt1228/chatgpt-java#211]

**Comment by youshandefeiyang** [comment]
Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@7b8fb9cf]
2023-10-20 09:10:55.500 ERROR 1587 --- [TaskExecutor-11] c.u.c.i.DynamicKeyOpenAiAuthInterceptor  : --------> 请求异常：{"error":{"code":502,"message":"Bad gateway.","param":null,"type":"cf_bad_gateway"}}
2023-10-20 09:10:55.501 ERROR 1587 --- [TaskExecutor-11] c.u.c.i.DynamicKeyOpenAiAuthInterceptor  : Bad gateway.
Exception in thread "TaskExecutor-11" com.unfbx.chatgpt.exception.BaseException: Bad gateway.
	at com.unfbx.chatgpt.interceptor.DynamicKeyOpenAiAuthInterceptor.intercept(DynamicKeyOpenAiAuthInterceptor.java:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.blockingGet(Single.java:2869)
	at com.unfbx.chatgpt.OpenAiClient.chatCompletion(OpenAiClient.java:656)
