### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by cqzaiercn** [Grt1228/chatgpt-java#35]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.ChatGPT.main(ChatGPT.java:16)
Caused by: org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j
	at org.apache.logging.slf4j.Log4jLoggerFactory.validateContext(Log4jLoggerFactory.java:49)
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:39)
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:30)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:53)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at com.unfbx.chatgpt.OpenAiClient.<clinit>(OpenAiClient.java:54)

**Comment by Grt1228** [comment]
日志jar包引入冲突了

**Comment by Grt1228** [comment]
日志包处理了下  可以更新到1.0.5版本再试试
